#!/usr/bin/env bash

set -eo pipefail

HOOK_DIR="$0.d"

for hook in "$HOOK_DIR"/*; do
	[ -x "$hook" ] || continue
	echo "Running hook: $(basename "$hook")"
	"$hook"
	status=$?
	if [[ $status -ne 0 ]]; then
		echo "Hook '$(basename hook)' failed with status $status" >&2
		exit $status
	fi
done

# vim: set filetype=sh:
